version: "3.7"
services:
  app:
    build:
      args:
        user: miracle
        uid: 1000
      context: docker/php-fpm/
      dockerfile: Dockerfile
    image: storage
    container_name: storage-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - storage
    extra_hosts:
      - "host.docker.internal:host-gateway"

  document-server:
    container_name: document-server
    image: onlyoffice/documentserver:7.5
    restart: unless-stopped
    ports:
      - 8080:80
    environment:
      JWT_SECRET: ${JWT_SECRET}
    networks:
      - storage

  db:
    image: mysql
    container_name: storage-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - ./docker/mysql:/var/lib/mysql
    networks:
      - storage

  nginx:
    image: nginx:alpine
    container_name: storage-nginx
    restart: unless-stopped
    ports:
      - 8000:80
    volumes:
      - ./:/var/www
      - ./docker/nginx/conf.d:/etc/nginx/conf.d/
    networks:
      - storage

  node:
    image: node:alpine
    container_name: storage-node
    restart: unless-stopped
    working_dir: /var/www/
    tty: true
    ports:
      - 5173:5173
    volumes:
      - ./:/var/www
    networks:
      - storage
        
networks:
  storage:
    driver: bridge